# BASIC CONFIG
term xterm-256color
shell_integration enabled
allow_hyperlinks yes
editor nvim
tab_bar_style powerline
tab_powerline_style slanted
window_padding_width 10
inactive_text_alpha 0.3
mouse_hide_wait 3.0

# Title bar
hide_window_decorations yes

# FONT
font_family FiraMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16.0
# text_composition_strategy legacy

# BACKGROUND
# background_opacity 0.9
# background_blur 9

# KEY MAPPING
map cmd+t new_tab_with_cwd !neighbor
map cmd+[ next_tab
map cmd+] previous_tab
map cmd+shift+] next_window
map cmd+shift+[ previous_window
# Navigate tab
# map cmd+1 goto_tab 1
# map cmd+2 goto_tab 2
# map cmd+3 goto_tab 3
# map cmd+4 goto_tab 4
# map cmd+5 goto_tab 5
# map cmd+6 goto_tab 6
# map cmd+7 goto_tab 7
# map cmd+8 goto_tab 8
# map cmd+9 goto_tab 9

# Install catpucin mocha themes
# include ./themes/mocha.conf

# Install kanagawa themes
# include ./themes/kanagawa_paper.conf

# Install gruvbox themes
include ./themes/gruvbox_dark_soft.conf

